# Generated by Django 6.0.5 on 2026-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='isarchived',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
