# Generated by Django 6.0.5 on 2026-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_user_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='isarchived',
            field=models.BooleanField(default=False),
        ),
    ]
