# Generated by Django 6.0.5 on 2026-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_isarchived'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
